/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BusinessAutomationRouteImport } from './routes/business-automation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as GrowingBusinessesRouteImport } from './routes/growing-businesses'
import { Route as HealthcareRouteImport } from './routes/healthcare'
import { Route as HealthcareRevenueCycleManagementRouteImport } from './routes/healthcare-revenue-cycle-management'
import { Route as HowWeWorkRouteImport } from './routes/how-we-work'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ManagedOperationsRouteImport } from './routes/managed-operations'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessAutomationRoute = BusinessAutomationRouteImport.update({
  id: '/business-automation',
  path: '/business-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowingBusinessesRoute = GrowingBusinessesRouteImport.update({
  id: '/growing-businesses',
  path: '/growing-businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRoute = HealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthcareRevenueCycleManagementRoute =
  HealthcareRevenueCycleManagementRouteImport.update({
    id: '/healthcare-revenue-cycle-management',
    path: '/healthcare-revenue-cycle-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const HowWeWorkRoute = HowWeWorkRouteImport.update({
  id: '/how-we-work',
  path: '/how-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagedOperationsRoute = ManagedOperationsRouteImport.update({
  id: '/managed-operations',
  path: '/managed-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/growing-businesses': typeof GrowingBusinessesRoute
  '/healthcare': typeof HealthcareRoute
  '/healthcare-revenue-cycle-management': typeof HealthcareRevenueCycleManagementRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/legal': typeof LegalRoute
  '/managed-operations': typeof ManagedOperationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/growing-businesses': typeof GrowingBusinessesRoute
  '/healthcare': typeof HealthcareRoute
  '/healthcare-revenue-cycle-management': typeof HealthcareRevenueCycleManagementRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/legal': typeof LegalRoute
  '/managed-operations': typeof ManagedOperationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/business-automation': typeof BusinessAutomationRoute
  '/contact': typeof ContactRoute
  '/growing-businesses': typeof GrowingBusinessesRoute
  '/healthcare': typeof HealthcareRoute
  '/healthcare-revenue-cycle-management': typeof HealthcareRevenueCycleManagementRoute
  '/how-we-work': typeof HowWeWorkRoute
  '/insights': typeof InsightsRoute
  '/legal': typeof LegalRoute
  '/managed-operations': typeof ManagedOperationsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/business-automation'
    | '/contact'
    | '/growing-businesses'
    | '/healthcare'
    | '/healthcare-revenue-cycle-management'
    | '/how-we-work'
    | '/insights'
    | '/legal'
    | '/managed-operations'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/business-automation'
    | '/contact'
    | '/growing-businesses'
    | '/healthcare'
    | '/healthcare-revenue-cycle-management'
    | '/how-we-work'
    | '/insights'
    | '/legal'
    | '/managed-operations'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/business-automation'
    | '/contact'
    | '/growing-businesses'
    | '/healthcare'
    | '/healthcare-revenue-cycle-management'
    | '/how-we-work'
    | '/insights'
    | '/legal'
    | '/managed-operations'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/terms-of-use'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  BusinessAutomationRoute: typeof BusinessAutomationRoute
  ContactRoute: typeof ContactRoute
  GrowingBusinessesRoute: typeof GrowingBusinessesRoute
  HealthcareRoute: typeof HealthcareRoute
  HealthcareRevenueCycleManagementRoute: typeof HealthcareRevenueCycleManagementRoute
  HowWeWorkRoute: typeof HowWeWorkRoute
  InsightsRoute: typeof InsightsRoute
  LegalRoute: typeof LegalRoute
  ManagedOperationsRoute: typeof ManagedOperationsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-automation': {
      id: '/business-automation'
      path: '/business-automation'
      fullPath: '/business-automation'
      preLoaderRoute: typeof BusinessAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growing-businesses': {
      id: '/growing-businesses'
      path: '/growing-businesses'
      fullPath: '/growing-businesses'
      preLoaderRoute: typeof GrowingBusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare': {
      id: '/healthcare'
      path: '/healthcare'
      fullPath: '/healthcare'
      preLoaderRoute: typeof HealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthcare-revenue-cycle-management': {
      id: '/healthcare-revenue-cycle-management'
      path: '/healthcare-revenue-cycle-management'
      fullPath: '/healthcare-revenue-cycle-management'
      preLoaderRoute: typeof HealthcareRevenueCycleManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-we-work': {
      id: '/how-we-work'
      path: '/how-we-work'
      fullPath: '/how-we-work'
      preLoaderRoute: typeof HowWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/managed-operations': {
      id: '/managed-operations'
      path: '/managed-operations'
      fullPath: '/managed-operations'
      preLoaderRoute: typeof ManagedOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  BusinessAutomationRoute: BusinessAutomationRoute,
  ContactRoute: ContactRoute,
  GrowingBusinessesRoute: GrowingBusinessesRoute,
  HealthcareRoute: HealthcareRoute,
  HealthcareRevenueCycleManagementRoute: HealthcareRevenueCycleManagementRoute,
  HowWeWorkRoute: HowWeWorkRoute,
  InsightsRoute: InsightsRoute,
  LegalRoute: LegalRoute,
  ManagedOperationsRoute: ManagedOperationsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfUseRoute: TermsOfUseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
